
<div class="header-language-background">
    <div class="header-language-container">
        <div class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php echo $this->getChildHtml('currency_switcher') ?>
            <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
    </div>
    <div class="clear"></div>
</div>

<header id="header" class="page-header">
    <div class="page-header-container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
<!--            <img src="--><?php //echo $this->getLogoSrc() ?><!--" alt="--><?php //echo $this->getLogoAlt() ?><!--" class="large" />-->
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>
        <div class="search-and-account-wrapper">
            <!-- Search -->
            <div class="header-search">
               <?php echo $this->getChildHtml('topSearch') ?>
            </div>
            <div class="clear"></div>
            <!-- Account -->
            <div class="header-account">
                <?php echo $this->getChildHtml('topLinks') ?>
            </div>
        </div>
        <div class="clear"></div>
        <!-- Navigation -->
        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
    </div>
</header>
<?php echo $this->getChildHtml('topContainer'); ?>
